var width = 8;
var height = 24;
var area = width * height;
console.log('area:', area);
console.log('typeof area:', typeof area);
var bill = 24.75;
var payment = 100;
var change = payment - bill;
console.log('change:', change);
console.log('typeof change:', typeof change);
var quizzes = 98;
var midterm = 91;
var final = 99;
var grade = (quizzes + midterm + final) / 3;
console.log('grade:', grade);
console.log('typeof grade:', typeof grade);
var firstName = 'Paxton';
var lastName = 'Rosenberg';
var fullName = firstName + ' ' + lastName;
console.log('fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
var pH = 8;
var isAcidic = pH < 7;
console.log('isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
var headCount = 24;
var isSparta = headCount === 300;
console.log('isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
var motto = fullName + ' is the GOAT';
console.log('motto:', motto);
console.log('typeof motto:', typeof motto);
